### PR TITLE
add support for Vietnamese reply format

### PR DESCRIPTION
**Pull request by hnx116**

### CODE REVIEW

**Comment by obukhov-sergey** [comment]
@mailgun-ci test this please

**Comment by obukhov-sergey** [comment]
@hnx116 thanks for the PR! Can you add tests as well?

**Comment by hnx116** [comment]
@obukhov-sergey Done

**Comment by obukhov-sergey** [comment]
@mailgun-ci test this please

**Comment by obukhov-sergey** [comment]
@hnx116 thanks, merged, I'll try to deploy it to prod this week (in case you're using the service and wondering).

**Comment by hnx116** [comment]
@obukhov-sergey thanks

**Pull request merged**
