### PR TITLE
Replace PyML with sklearn and clean up dependencies 

### PR DESCRIPTION
**Pull request by AlexRiina**
Locally all but the iphone case of `test_standard_replies` pass which seems to be due to `extract_signature` missing from those tests.

Thanks @scottmac for getting the android test working!

### CODE REVIEW

**Comment by scottmac** [comment]
I'm curious if the iphone test in test_standard_replies is ever passing in the main. But I can't get PyML installed to test.

**Comment by oliversong** [comment]
Any plans on continuing this? I'm having PyML issues as well.

**Comment by oliversong** [comment]
@scottmac The iphone test does pass in mailgun's master

**Comment by oliversong** [comment]
@AlexRiina the last test is fixed here- https://github.com/AlexRiina/talon/pull/2

**Comment by obukhov-sergey** [comment]
@AlexRiina @oliversong @scottmac thank you all for your interest in the library and the effort!

**Pull request merged**
