### PR TITLE
Support for German & Dutch + better handling of +1000 lines mails

### PR DESCRIPTION
**Pull request by simonflore**
Extra support for German and NL

### CODE REVIEW

**Comment by simonflore** [comment]
Any reason why these changes can't be merged?

**Comment by steffenmllr** [comment]
Better support for German would be really great!

**Comment by tgwizard** [comment]
Hi,

I've created a fork of talon, https://github.com/tictail/claw, in which I've removed the signature extraction that depends on ML (which I didn't use), and cleaned up some dependencies (now much less weird stuff installed). I've also started to implement some bug fixes, along with CI test suites and so on.

@simonflore if you like, I'd love to include this PR in claw. Would you mind submitting it there as well?

**Comment by simonflore** [comment]
@tgwizard Good idea. It looks like Mailgun isn't actively supporting Talon.

**Comment by obukhov-sergey** [comment]
Applied in https://github.com/mailgun/talon/pull/56 and fixed the failing test.

**Pull request closed without merging**
