### PR TITLE
Fix catastrophic backtracking in regexp

### PR DESCRIPTION
**Pull request by ad-m**
Co-Author: @Nipsuli

Fix for https://github.com/mailgun/talon/issues/168 .

### CODE REVIEW

**Comment by obukhov-sergey** [comment]
@mailgun-ci test this please

**Comment by obukhov-sergey** [comment]
@mailgun-ci test this please

**Comment by obukhov-sergey** [comment]
@mailgun-ci test this please

**Comment by obukhov-sergey** [comment]
@mailgun-ci retest this please

**Comment by highlycaffeinated** [comment]
@mailgun-ci retest this please

**Comment by ad-m** [comment]
@mailgun-ci , could you test that finally?

**Comment by obukhov-sergey** [comment]
@mailgun-ci retest this please

**Comment by obukhov-sergey** [comment]
@mailgun-ci retest this please

**Comment by powellchristoph** [comment]
@mailgun-ci test this please

**Comment by powellchristoph** [comment]
@mailgun-ci test this please

**Comment by powellchristoph** [comment]
@mailgun-ci retest this please

**Comment by powellchristoph** [comment]
@mailgun-ci test this please

**Comment by powellchristoph** [comment]
@mailgun-ci test this please

**Comment by ad-m** [comment]
@powellchristoph , could you help to setup working CI environment? It looks that mailgun have a serious problem with own CI platform.

**Comment by ad-m** [comment]
@powellchristoph, could I help to setup working CI environment eg. on TravisCI / CircleCI? It looks that mailgun have a serious problem with own CI platform.

**Comment by obukhov-sergey** [comment]
@mailgun-ci test this please

**Comment by obukhov-sergey** [comment]
@mailgun-ci retest this please

**Comment by powellchristoph** [comment]
@ci test this please

**Comment by powellchristoph** [comment]
@mailgun-ci test this please

**Comment by powellchristoph** [comment]
@ad-m  Thank you for the offer and my apologies for the delay. We do appreciate the contribution.

**Pull request merged**
