### PR TITLE
Python 3 compatibility up to 3.6.1

### PR DESCRIPTION
**Pull request by yfilali**
This is to resolve issue #42.

The notable parts to take a good look at is the return type where some of the functions are returning byte arrays but the tests were asserting against strings which failed. 

Also, some of the functions took bytearrays only and are now taking strings as well.

### CODE REVIEW

**Comment by ad-m** [comment]
@mailgun-ci , do you can link the report, please?

**Comment by yfilali** [comment]
@ad-m improved it a bit since initial commit to handle permission errors when trying to write the python 3 converted classifier. It used a temp file as a fallback now.

**Comment by obukhov-sergey** [comment]
@mailgun-ci test this please

**Comment by obukhov-sergey** [comment]
@mailgun-ci test this please

**Pull request merged**
