### PR TITLE
Add __init__.py into data folder, add data files into MANIFEST.in

### PR DESCRIPTION
**Pull request by yoks**
This changes enable to use pip git link directly from the repo, e.g.
```
git+git://github.com/yoks/talon/@58eac88a10c4956cd3d1ccee38fde4a71c571804
```

Without this changes, pip does not pull data files.

### CODE REVIEW

**Comment by obukhov-sergey** [comment]
@mailgun-ci test this please

**Comment by kaivanov** [comment]
retest this please

**Comment by kaivanov** [comment]
ok to test

**Comment by kaivanov** [comment]
retest this please

**Comment by kaivanov** [comment]
retest this please

**Pull request merged**
