### PR TITLE
Add better support for Scandinavian languages

### PR DESCRIPTION
**Pull request by tgwizard**
This is a port of https://github.com/tictail/claw/pull/6 by @simonflore.

### CODE REVIEW

**Comment by tgwizard** [comment]
@obukhov-sergey could you please have a look at this PR?

**Comment by tgwizard** [comment]
Bump

**Comment by tgwizard** [comment]
Could someone at Mailgun or with commit privileges please review this PR?

**Comment by simonflore** [comment]
I'm guessing they don't really understand what Github is about.

**Comment by tgwizard** [comment]
@obukhov-sergey could you please review this PR?

**Pull request merged**
