### PR TITLE
Polymail Quote Support

### LINKED ISSUE #134: Quotes extraction failed with Polymail replies
Replies initiated from [polymail](https://polymail.io/) do not extract the quoted text.

Steps to reproduce:
1. Send a message to yourself using polymail
2. Read that message in gmail and reply to it
3. Read the message in polymail and reply to it
4. Get the original message and test on [talon testing site](http://talon.mailgun.net/).

Example:
```
Return-Path: <xxxx@gmail.com>
Received: from localhost (ec2-54-158-139-194.compute-1.amazonaws.com. [54.158.139.194])
        by smtp.gmail.com with ESMTPSA id q32sm10037057qtd.5.2017.04.11.19.08.54
        for <xxxx@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 11 Apr 2017 19:08:55 -0700 (PDT)
Mime-Version: 1.0
X-Mailer: Polymail
Message-ID: <58ed8c0700bfbb00001339d3@polymail.io>
Subject: Re: Test
From: Ethan Setnik <xxxxgmail.com>
To: Ethan Setnik <xxxx@gmail.com>
Date: Tue, 11 Apr 2017 19:08:45 -0700
In-Reply-To: <CAKzr07V771zMRYAE9m9yU1NqnGGtkbmUSOvWWz84J2O+i5-ubg@mail.gmail.com>
References: <CAKzr07V771zMRYAE9m9yU1NqnGGtkbmUSOvWWz84J2O+i5-ubg@mail.gmail.com>
Content-Type: multipart/alternative; boundary=379c710cb6a99096f577366db69dccf23b4f785368751bb5acb86a2e162a

--379c710cb6a99096f577366db69dccf23b4f785368751bb5acb86a2e162a
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain; charset=UTF-8

This is the reply from Polymail

On Tue, Apr 11, 2017 at 10:07 PM Ethan Setnik

<
mailto:Ethan Setnik <xxxx@gmail.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

This is the reply

On Tue, Apr 11, 2017 at 10:07 PM Ethan Setnik <
mailto:xxxx@gmail.com
> wrote:

This is the initial message
--379c710cb6a99096f577366db69dccf23b4f785368751bb5acb86a2e162a
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

<img style=3D"border: none; background:none; width: 0; height: 0;" src=3D"h=
ttps://share.polymail.io/v2/z/a/NThlZDhjMDcwMGJm/y6ry9vAsZIPxUbBfihWq6SToKm=
8ok2BlbhzkP296GDPgMIHiWWU4BGEw66uif81ucgL4a8UOrQQwwC_UjBeGCbM9In5alO4MMVE8t=
vBv8AZYGvniUINmkwConAMIHC8HJqpDarTqW6RRpNOc.png" alt=3D"" width=3D"0px" hei=
ght=3D"0px" border=3D"0" /><div></div>
<div>
This is the reply from Polymail<br><br>
</div>
<div id=3D"psignature"><br></div>
<div class=3D"gmail_extra"><br><div class=3D"gmail_quote"><div dir=3D"ltr">=
On Tue, Apr 11, 2017 at 10:07 PM Ethan Setnik <xxxxx@gmail.com> &lt;<a hr=
ef=3D"mailto:Ethan Setnik <xxxxx@gmail.com>">Ethan Setnik <xxxxx@gmail.=
com></a>&gt; wrote:<br></div><blockquote class=3D"gmail_quote" style=3D"mar=
gin:0 0 0 .8ex;border-left:1px #ccc solid;padding-left:1ex"><!DOCTYPE html>=
<html><head><meta name=3D"viewport" content=3D"width=3Ddevice-width"><style=
>a, pre, code, a:link, body { word-wrap: break-word !important; }</style></=
head><body>
<div dir=3D"ltr">This is the reply</div>
<br><div class=3D"gmail_quote"></div>
</body></html><div dir=3D"ltr">On Tue, Apr 11, 2017 at 10:07 PM Ethan Setni=
k &lt;<a href=3D"mailto:xxxxx@gmail.com">xxxxx@gmail.com</a>&gt; wrote:=
<br></div><blockquote class=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;bord=
er-left:1px #ccc solid;padding-left:1ex"><img style=3D"border:none;backgrou=
nd:none;width:0;height:0" src=3D"https://ci4.googleusercontent.com/proxy/JX=
XTuFue-6g3aDYP_klLyNmTSWdgpANzRviNIzs2xpEC3ZMdoU8vXxg9DwFJpUnjRTFU6s4roA3f7=
IW_t3ZahYdgJo_3GAl4qZoNqEse6VsyfI6rmoLF5dB2iRmlV1GUNQgdinzLxOFTi_ycHjBzJQ-r=
vKcMqnQAw3tD9GyeqniSbhysEgK2xMhP4OakJkFptqHAzVbC3TClDGj_UN617anYUW0043qgREP=
JDoT0wBMyTqNruExX68G_alPEZjE-VN3Xr_X3sb4EwxlEoIEU30xD9KHS7tnGwkB9BN0=3Ds0-d=
-e1-ft#https://share.polymail.io/v2/z/a/NThlZDhiYjVjZDU1/OoigMTRZhepebW8cok=
gLWKlfeOn7lYi8eweMZ5IXUoacBlsPJJOLaoXSc0u1N-c2QTywVrJgUzzUmzFmBx1UwiHWkaj_W=
gHTH6qG4m-Eo_t1ETpIvzwZKvwaUKsm_3VFDUQj4i5HZZojujdK.png" alt=3D"" width=3D"=
0px" height=3D"0px" border=3D"0" class=3D"gmail_msg">This is the initial me=
ssage</blockquote></div></div></blockquote></div><br></div>
--379c710cb6a99096f577366db69dccf23b4f785368751bb5acb86a2e162a--
```

### PR DESCRIPTION
**Pull request by esetnik**
Resolves #134

### CODE REVIEW

**Comment by obukhov-sergey** [comment]
@mailgun-ci test this please

**Comment by obukhov-sergey** [comment]
@esetnik thanks for the PR! Can you plz fix a failing test:

```
======================================================================
FAIL: tests.utils_test.test_detect_encoding
----------------------------------------------------------------------
Traceback (most recent call last):
...
tests/utils_test.py", line 32, in test_detect_encoding
    eq_ ('iso-8859-2', u.detect_encoding(u'Versi\xf3n'.encode('iso-8859-2')).lower())
AssertionError: 'iso-8859-2' != 'iso-8859-1'
```

I'd suggest changing it to something like:

```python
ok_(u.detect_encoding(u'Versi\xf3n'.encode('iso-8859-2')).lower() in ['iso-8859-1', 'iso-8859-2'])
```

unless you have a better idea.

**Comment by esetnik** [comment]
Hmm I noticed that test was failing but thought it was due to my platform. Is this test failure introduced by my PR or you just want to bundle that fix?

**Comment by esetnik** [comment]
TBH I'm not even really sure what that test is testing but it looks like it should be returning the encoding used to encode `u'Versi\xf3n'` so I do not think it's correct to check whether the encoding passed in matches `['iso-8859-1', 'iso-8859-2']`. I think it's more likely that `detect_encoding` is returning the wrong encoding.

**Comment by obukhov-sergey** [comment]
@mailgun-ci test this please

**Comment by obukhov-sergey** [comment]
@esetnik I've fixed the test in a separate [PR](https://github.com/mailgun/talon/pull/137). The failing test had nothing to do with your changes. We try not to freeze dependencies versions and for the test the chardet library was updated automatically. Tests with libraries that guess encoding can be flaky. You can check out the PR for a more detailed explanation, options considered, etc.

**Comment by obukhov-sergey** [comment]
@esetnik fyi, I bumped talon version to 1.3.7 and uploaded it to PyPi, thanks for the PR!

**Pull request merged**
